name: Autograding Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytest

      # Module 1.1 (5 marks)
      - name: M1_1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m1_1.py || true
          max-score: 5

      # Module 1.2 (5 marks)
      - name: M1_2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m1_2.py || true
          max-score: 5

      # Module 2.1 (5 marks)
      - name: M2_1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m2_1.py || true
          max-score: 5

      # Module 2.2 (5 marks)
      - name: M2_2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m2_2.py || true
          max-score: 5

      # Remaining 8 modules (8 marks each)
      - name: M3_1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m3_1.py || true
          max-score: 8

      - name: M3_2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m3_2.py || true
          max-score: 8

      - name: M3_3
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m3_3.py || true
          max-score: 8

      - name: M4
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m4.py || true
          max-score: 8

      - name: M5_1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m5_1.py || true
          max-score: 8

      - name: M5_2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m5_2.py || true
          max-score: 8

      - name: M5_3
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m5_3.py || true
          max-score: 8

      - name: M6_1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m6_1.py || true
          max-score: 8

      - name: M6_2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m6_2.py || true
          max-score: 8

      - name: M6_3
        uses: classroom-resources/autograding-python-grader@v1
        with:
          entryPoint: pytest
          args: tests/test_m6_3.py || true
          max-score: 8

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: M1_1,M1_2,M2_1,M2_2,M3_1,M3_2,M3_3,M4,M5_1,M5_2,M5_3,M6_1,M6_2,M6_3