name: Autograding

'on':
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install pytest

      # ----------------- Module 1 -----------------
      - name: Run tests for m1_1
        id: m1-1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m1_1.py
          timeout: 20
          max-score: 5

      - name: Run tests for m1_2
        id: m1-2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m1_2.py
          timeout: 20
          max-score: 5

      # ----------------- Module 2 -----------------
      - name: Run tests for m2_1
        id: m2-1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m2_1.py
          timeout: 20
          max-score: 5

      - name: Run tests for m2_2
        id: m2-2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m2_2.py
          timeout: 20
          max-score: 5

      # ----------------- Module 3 -----------------
      - name: Run tests for m3_1
        id: m3-1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m3_1.py
          timeout: 20
          max-score: 5

      - name: Run tests for m3_2
        id: m3-2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m3_2.py
          timeout: 20
          max-score: 5

      - name: Run tests for m3_3
        id: m3-3
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m3_3.py
          timeout: 20
          max-score: 5

      # ----------------- Module 4 -----------------
      - name: Run tests for m4_1
        id: m4-1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m4_1.py
          timeout: 20
          max-score: 5

      # ----------------- Module 5 -----------------
      - name: Run tests for m5_1
        id: m5-1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m5_1.py
          timeout: 20
          max-score: 15

      - name: Run tests for m5_2
        id: m5-2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m5_2.py
          timeout: 20
          max-score: 15

      - name: Run tests for m5_3
        id: m5-3
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m5_3.py
          timeout: 20
          max-score: 15

      # ----------------- Module 6 -----------------
      - name: Run tests for m6_1
        id: m6-1
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m6_1.py
          timeout: 20
          max-score: 10

      - name: Run tests for m6_2
        id: m6-2
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m6_2.py
          timeout: 20
          max-score: 10

      - name: Run tests for m6_3
        id: m6-3
        uses: classroom-resources/autograding-python-grader@v1
        with:
          test-command: pytest -q tests/test_m6_3.py
          timeout: 20
          max-score: 10

      # ----------------- Reporter -----------------
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: |
            m1-1
            m1-2
            m2-1
            m2-2
            m3-1
            m3-2
            m3-3
            m4-1
            m5-1
            m5-2
            m5-3
            m6-1
            m6-2
            m6-3